services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: tbot-api-gateway
    ports:
      - "4000:4000"

  ui-flask:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: tbot-ui-flask
    depends_on:
      - api-gateway
    ports:
      - "5000:5000"
